# Generated by Django 4.2 on 2025-01-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
