# Generated by Django 4.2 on 2025-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsweet', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fb',
            field=models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
