# Generated by Django 4.2 on 2025-01-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsweet', '0007_author_fb_author_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ig',
            field=models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='ln',
            field=models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='x',
            field=models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
